### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (320,320) (3,) 

### ISSUE THREAD

**Issue by SalimFares4** [SalimFares4/Image-Segmentation#10]
I'm trying to re-implement the model in [this repository](https://github.com/qubvel/segmentation_models.pytorch) to make it work on our dataset in [this file](https://github.com/SalimFares4/Image-Segmentation/blob/main/Code/Segmentation_Model.ipynb).
I'm getting an error at this line 'train_logs = train_epoch.run(train_loader)' which apparently is caused by  'get_preprocessing' 
function.
@dAgbeve @handraleaditya  @seifeddineidani

**Comment by handraleaditya** [comment]
Did you solve it? 
Sorry im just seeing this now
